{  
    "icosa" : {
        "mirror_urls": {},
        "configs": {},
    },
    "foster" : {
        "mirror_urls": {},
        "configs": {},
    },
    "foster_tab" : {
        "mirror_urls": {},
        "configs": {},
    },
}
